webcat12345/ngx-ui-switch

README.md, package.json, src/ui-switch.component.ts
=> issue #12 - upgrade dependencies to latest

package.json
=> chore(package): update webpack-dev-server to version 2.4.5

package.json
=> chore(package): update rxjs to version 5.4.0

src/ui-switch.component.ts
@Input() defaultBgColor: string = '#fff';
@Input() defaultBoColor: string = '#dfdfdf';
For set color off switch parametrs.
example:
defaultBgColor="red"
=> Add: set defaultBgColor or set defaultBoColor

package.json
=> chore(package): update @angular/common to version 4.3.4

package.json
=> chore(package): update @angular/compiler to version 4.3.4

package.json
=> chore(package): update @angular/core to version 4.3.5

package.json
=> chore(package): update @angular/forms to version 4.3.4

build.ts, package.json, src/lib/package.json
=> Fix build process bug with yarn and npm

.all-contributorsrc, README.md, package.json, yarn.lock
=> chore(contributors): Add contributors to README

.gitignore, README.md, src/app/app.module.ts, src/lib/ui-switch/ui-switch.module.ts
=> fix(ui-switch-module): Import FormsModule

README.md, package.json, src/lib/ui-switch/ui-switch.component.ts, src/lib/ui-switch/ui-switch.config.ts, src/lib/ui-switch/ui-switch.module.ts, src/lib/ui-switch/ui-switch.token.ts
Hello,
I added option to set up global options as requested in #252
Enjoy
=> feat(#252) Option to set up global settings

README.md, angular.json, package.json, src/app/demo/demo.component.html, src/app/demo/demo.component.spec.ts, src/lib/ui-switch/ui-switch.component.ts
Added the ability to add content to the switch so its customizable.
You can add
- web fonts
- images
- animations
- custom html
This closes feature request #311 and doesn't introduce any breaking changes.
=> Added the ability to add content to the switch so its customizable.

package-lock.json, src/lib/ui-switch/ui-switch.component.ts
Span converted to a button for accessibility purposes. Being able to TAB through the component.
=> Converting span into button for accessibility

src/lib/ui-switch/ui-switch.module.ts
=> angular 9 support

src/lib/ui-switch/ui-switch.component.scss, src/styles.scss
=> fix(switch): Fix switch label display for button

build.ts, package.json, src/lib/tsconfig-build.json, src/tsconfig.app.json, yarn.lock
* Opts out of ivy for building package
https://github.com/angular/angular/issues/35255
=> Upgrade to Angular 9

src/lib/ui-switch/ui-switch.component.html
=> fix(form): Add type=button

src/lib/ui-switch/ui-switch.component.ts
=> fix(beforeChange): Skip beforeChange when disabled

build.ts, src/app/app.component.spec.ts, src/app/app.component.ts, src/app/app.module.ts, src/app/demo-cdr/demo-cdr.component.spec.ts, src/app/demo/demo.component.spec.ts, src/app/footer/footer.component.spec.ts, src/app/github-link/github-link.component.spec.ts, src/app/header/header.component.spec.ts, src/lib/ui-switch/ui-switch.component.ts, tsconfig.json, tslint.json
=> chore(lint): Update tslint rules

.gitignore, angular.json, package.json, src/app/app.module.ts, src/lib/tsconfig-build.json, src/polyfills.ts, src/test.ts, tsconfig.json, yarn.lock
- Ng update to 12
- Ng update to 13
- Update browserlist DB
- Increase package.json version 13.0.0
=> Upgrade to Angular 13

scripts/publish.sh
First pass at script for version bumping
Will probably extract out into Make or npm scripts.
=> build(scripts): Add publish script
